package day42_Exceptions;

import javax.crypto.ExemptionMechanismException;

public class ThrowsKeyword {

        public static void main(String[] args)throws InterruptedException {
    //public static void main(String[] args)throws InterruptedException, ExemptionMechanismException {
// we can use mor than one exception




//        System.out.println("_----------------------------- Test 1-------------------");
//        System.out.println("Hello");
//
//        try {
//            Thread.sleep(3000);
//        } catch (InterruptedException e) {
//            e.printStackTrace();
//        }
//
//        System.out.println("Cydeo");
//
//
//        System.out.println("------------- test 1 completed ------------------------------");
//
//        System.out.println("--------------------- test 2 -------------------------");
//        System.out.println("Hello");
//
//        try {
//            Thread.sleep(3000);
//        } catch (InterruptedException e) {
//            e.printStackTrace();
//        }
//
//        System.out.println("Batch25");
//
//        System.out.println("------------- test 2 completed ------------------------------");
//

        System.out.println("_----------------------------- Test 1-------------------");
        System.out.println("Hello");


            Thread.sleep(3000);


        System.out.println("Cydeo");


        System.out.println("------------- test 1 completed ------------------------------");

        System.out.println("--------------------- test 2 -------------------------");
        System.out.println("Hello");


            Thread.sleep(3000);


        System.out.println("Batch25");

        System.out.println("------------- test 2 completed ------------------------------");
























    }
}
